name: DBT Review Deployment
run-name: Deploying DBT in review env ${{ github.actor }} 🚀
on:
  pull_request:
    branches:
      - main
env:
  GCP_PROJECT_ID: jbs-lab
  GCP_DBT_CI_SA_KEY_FILE: ./gcp_dbt_ci_sa.json
  GCP_DBT_CI_SA: ${{ secrets.GCP_DBT_CI_SA }}
  DBT_PROFIL_DIR: ./strava_dbt


jobs:

  init-env:
    uses: jrmbrgs/strava-stats/.github/workflows/dbt-setup.yaml@dbt
    with:
      env-name: "review"
      GCP_DBT_CI_SA_KEY_FILE: ./gcp_dbt_ci_sa.json
    secrets:
      GCP_DBT_CI_SA: ${{ secrets.GCP_DBT_CI_SA }}


  dbt-deploy-review:
    needs: init-env
    environment: review
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v1
        with:
          python-version: "3.11.x"

      - name: Run Dbt models
        run: |
          cd $DBT_PROFIL_DIR
          dbt run --target review --project-dir ./ --profiles-dir ./

      - name: Test Dbt models
        run: |
          cd $DBT_PROFIL_DIR
          dbt test --target review --project-dir ./ --profiles-dir ./
